# Day 4: Pre-processing Techniques

In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [21, None, 23, 24],
    'Score': [80, 75, None, 95]
}

df = pd.DataFrame(data)
df

      Name   Age  Score
0    Alice  21.0   80.0
1      Bob   NaN   75.0
2  Charlie  23.0    NaN
3    David  24.0   95.0

In [2]:
df_dropped = df.dropna()
df_dropped

    Name   Age  Score
0  Alice  21.0   80.0
3  David  24.0   95.0

In [3]:
df_filled = df.copy()

df_filled['Age'] = df_filled['Age'].fillna(df_filled['Age'].mean())
df_filled['Score'] = df_filled['Score'].fillna(0)

df_filled

      Name        Age  Score
0    Alice  21.000000   80.0
1      Bob  22.666667   75.0
2  Charlie  23.000000    0.0
3    David  24.000000   95.0

## Reflection

Filling missing values is better than dropping rows because dropping removes valuable data and reduces dataset size.

Using mean for numerical values like age maintains realistic distribution, whereas filling with 0 introduces incorrect data and biases the model.

Thus, imputation helps preserve both data quantity and quality.